version: '3'
services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: app1
  app2:
    build:
      context: './app2'
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    container_name: app2