version: '3'

services:
  my-ionic-app:
    image: "lauraelena/my-ionic-app"
    build:
      context: ./my-ionic-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  my-nest-app-2:
    image: "lauraelena/my-nest-app-2"
    build:
      context: ./my-nest-app-2
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  app1:
    build:
      context: ./basic-host-remote/app1
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: app1
  app2:
    build:
      context: './basic-host-remote/app2'
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    container_name: app2